---
title: Product Design Operating System
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  plays:
    title: plays
    permalink: /:title
    output: true
email: hello@anothertompetty.com
description: Goes here
baseurl: "/product-design-playbook"
url: http://playbook.tom.pe
twitter_username: tp
github_username: anothertompetty
markdown: kramdown
